default: true

# MD007/ul-indent
# unordered-list-indent
MD007:
    indent: 4

# MD013/line-length
MD013: false

# MD014/commands-show-output
MD014: false

# MD024/no-duplicate-heading
MD024:
    # Duplication is allowed with different parents. (e.g. changelogs):
    siblings_only: true

# MD022/blanks-around-headings
# Headings should be surrounded by blank lines
MD022:
    # Blank lines above heading
    lines_above: 1
    # Blank lines below heading
    lines_below: 1

# MD033/no-inline-html
MD033: false

# MD041/first-line-h1
MD041: false

# MD046/code-block-style
# Different code block styles are allowed
MD046: false

# MD059/descriptive-link-text
# "here", "link" are not descriptive link texts.
MD059: false
