[project]
name = "cpp-dev"
version = "0.1.0"
description = "C++ Development Environment"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[activation]
scripts = ["context/setup.sh"]

[activation.env]
LD_LIBRARY_PATH = "${PIXI_PROJECT_ROOT}/lib:$LD_LIBRARY_PATH"

[dependencies]
# C++17 minimum requirement: clang >= 5.0, gcc >= 7.0, MSVC >= 19.14 (VS2017)
clang = "==21.1.1"  # Latest stable version - available on all platforms
lld = "==21.1.1"  # LLVM linker
clang-tools = "==21.1.1"  # Includes: clang-tidy, clang-format, clangd
cppcheck = "==2.18.3"  # Static analysis tool
cmake = "==4.1.1"  # Build system generator
ninja = "==1.13.1"  # Build system
typos = ">=1.36.3,<2"  # Spell checker
sccache = ">=0.10.0,<0.11"  # C/C++ compiler cache

[target.linux-64.dependencies]
gcc = "==15.1.0"  # GCC compiler
gxx = "==15.1.0"  # G++ compiler
libgcc-ng = "==15.1.0"  # GCC runtime library
libstdcxx-ng = "==15.1.0"  # C++ standard library

[target.win-64.dependencies]
clang_win-64 = "==21.1"  # Clang cross-compiler for Windows
clangxx_win-64 = "==21.1"  # Clang++ cross-compiler for Windows
# MSYS2/MinGW related packages
m2w64-sysroot_win-64 = "==12.0.0.r4.gg4f2fc60ca"  # System root for MinGW-w64
m2-gcc-libs = "==13.3.0.1"  # GCC runtime libraries
libgcc-devel_win-64 = "==15.1.0"  # GCC development libraries

[tasks]
# Main development tasks
config = "cmake --preset=release"
config-debug = "cmake --preset=debug"
build = "cmake --build build -j 8"
test = "ctest --test-dir build"
clean = "cmake --build build --target clean"
format = "cmake --build build --target format"
lint = "cmake --build build --target lint"
run-cppcheck = "cmake --build build --target run-cppcheck"
fullcheck = "pixi run typos && pixi run lint && pixi run run-cppcheck"
